### ISSUE TITLE
Multiple SAM template function support

### ISSUE THREAD

**Issue by alteredtech** [swift-server/swift-openapi-lambda#18]
I was wondering if it is possible for multiple function definitions in the sam template. Currently it seems like it just proxies everything to the server that then does the routing (if my understanding is correct). As I currently understand, the current method would require a different executable defined in the package, which would also mean an `openapi.yaml` and `openapi-generator-config.yaml` file for each executable even though they are sharing the same file.

Instead of 

```
Resources:
  # Lambda function
  PetStore:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        # pass through all HTTP verbs and paths
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
```

To

```
Resources:
  GetPetbyId:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: <Whatever this would be>
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: get
            Path: /pet/{petId}
  GetPetsbyTags:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: <Whatever this would be>
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: get
            Path: /pet/findbytags
  GetPetsbyStatus:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: <Whatever this would be>
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: get
            Path: /pet/findbyStatus
  UpdatePet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: <Whatever this would be>
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: put
            Path: /pet
  AddPet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: <Whatever this would be>
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: post
            Path: /pet
```
